import type { ComponentType, ReactNode } from 'react';

// View Registry types

// 视图挂载点。对外可用的只有 sidebar 和 bottom：
// - sidebar: 左侧面板，由 NavRail 切换
// - bottom: 终端底部 tab，由 BottomTabBar 切换
// center 和 agent 被 builtin 常驻挤占（见 App.tsx 渲染逻辑 + builtinViews.tsx），插件实际无法使用。
export type MountPoint = 'sidebar' | 'center' | 'bottom' | 'agent';
export type NavGroup = 'top' | 'bottom';

export type ViewIcon =
  | { kind: 'react'; node: ReactNode }
  | { kind: 'svg'; path: string }
  | { kind: 'img'; src: string };

export interface ViewProvider {
  id: string;
  pluginId: string;
  mount: MountPoint;
  title: string;
  icon: ViewIcon;
  navGroup?: NavGroup;
  order: number;
  exclusive?: boolean;
  component: () => Promise<{ default: ComponentType }>;
  webviewEntry?: string;
}

// Plugin manifest types

export type IconKind = 'svg' | 'img' | 'emoji';
export type ToolKind = 'ssh' | 'local';
export type RunAt = 'idle' | 'instant';
export type PluginViewMount = 'sidebar' | 'settings';

export interface PluginIconDef {
  kind: IconKind;
  src: string;
}

export interface PluginViewDef {
  id: string;
  mount: PluginViewMount;
  title: string;
  icon?: PluginIconDef;
  navGroup?: NavGroup;
  order: number;
  entry: string;
  exclusive?: boolean;
}

export interface PluginAgentToolDef {
  name: string;
  description: string;
  command: string;
  kind?: ToolKind;
  handler?: string;
  parameters?: unknown;
  riskLevel?: RiskLevel;
}

/**
 * A content-script injection entry. The plugin's JS runs inside the main
 * window and can manipulate the DOM freely (IPC calls still go through the
 * capability-checked proxy). CSS is injected as a global `<style>` tag.
 */
export interface PluginInjectionDef {
  /** Unique id within the plugin (e.g. "main-ui"). */
  id: string;
  /**
   * Which main-UI regions this injection targets. Values match `data-region`
   * attributes: "sidebar" / "center" / "agent" / "terminal" / "settings" /
   * "sessions" / "skills" / "mcp" / "agent-panel". "*" means always inject.
   */
  matches: string[];
  /** CSS file paths relative to the plugin root, injected as `<style>` tags. */
  styles: string[];
  /** JS file paths relative to the plugin root, executed with the `marcel`
   *  runtime API as the argument. */
  scripts: string[];
  /** When to inject: "idle" (default) or "instant". */
  runAt: RunAt;
  /** Sort weight for multi-plugin ordering (lower = earlier). */
  order: number;
}

export interface PluginManifest {
  id: string;
  version: string;
  name: string;
  publisher?: string;
  description?: string;
  capabilities: string[];
  views: PluginViewDef[];
  agentTools: PluginAgentToolDef[];
  configView?: string;
  /** Content-script injections. Requires the `ui.inject` capability. */
  injections: PluginInjectionDef[];
  /**
   * Minimum app version this plugin is compatible with (optional). When the
   * running app version is lower, the plugin is auto-disabled: the backend
   * refuses to load it and the settings UI shows the required version.
   */
  minAppVersion?: string;
  /** Relative paths preserved across updates (e.g. config.json, memories/). */
  preservePaths?: string[];
}

export interface PluginHttpRequest {
  url: string;
  method?: string;
  headers?: Record<string, string>;
  body?: string;
}

export interface PluginHttpResponse {
  status: number;
  headers: Record<string, string>;
  body: string;
  url: string;
}

/** Market icon: emoji glyph or https image URL. */
export interface MarketIcon {
  kind: 'emoji' | 'img';
  value: string;
}

/** One plugin entry in the market index (generated by the market repo bot). */
export interface MarketPlugin {
  id: string;
  name: string;
  version: string;
  publisher: string;
  minAppVersion?: string | null;
  description: string;
  capabilities: string[];
  category: string;
  icon?: MarketIcon | null;
  repoUrl: string;
  updatedAt: string;
}

/** Market index document served by the market repository. */
export interface MarketIndex {
  generatedAt: string;
  plugins: MarketPlugin[];
}

/** Detail payload: plugin.json + README.md from the plugin's GitHub repo. */
export interface MarketDetail {
  manifest: PluginManifest | null;
  readme: string | null;
}

/** Result of `plugin_install`. The plugin takes effect after a restart. */
export interface PluginInstallResult {
  id: string;
  name: string;
  version: string;
  restartRequired: boolean;
}

/** Progress pushed by `plugin_install` via `plugin-install-progress` events.
 *  `phase: "downloading"` uses byte counts; `phase: "extracting"` uses zip
 *  entry counts. `total === 0` means unknown (indeterminate progress bar). */
export interface PluginInstallProgress {
  installId: string;
  phase: 'downloading' | 'extracting';
  received: number;
  total: number;
}

/**
 * Diff returned by `plugin_reload` / emitted via `plugin-registry-changed`.
 * `changed` lists plugin ids whose manifest or enabled-state changed since the
 * previous reload; `removed` lists ids no longer on disk. Callers should
 * destroy/recreate webviews + injections for these plugins only (incremental
 * refresh instead of nuke-and-rebuild).
 */
export interface ReloadDiff {
  allIds: string[];
  changed: string[];
  removed: string[];
}

// Connection types

export interface JumpConfig {
  host: string;
  port: number;
  username: string;
  authMethod: AuthMethod;
}

export interface ConnectionConfig {
  host: string;
  port: number;
  username: string;
  authMethod: AuthMethod;
  /** Saved connection ID, used by Agent tools for password lookup (sudo auto-fill). */
  connectionId?: string;
  /**
   * User has explicitly opted to trust a new (mismatching) host key. Only set
   * after the user confirms the HostKeyMismatch modal. Drives the backend to
   * `KnownHostsStore::replace` instead of rejecting the handshake.
   */
  trustNewHostKey?: boolean;
  /** Optional ProxyJump hop. */
  jump?: JumpConfig;
}

export type AuthMethod =
  | { type: 'Password'; password: string }
  | { type: 'PrivateKey'; keyPath: string; passphrase?: string }
  | { type: 'Agent' };

/** Jump auth mode stored on SavedConnection (not runtime credentials). */
export type JumpAuthMethod = 'withTarget' | 'Password' | 'PrivateKey';

export interface SavedConnection {
  id: string;
  name: string;
  host: string;
  port: number;
  username: string;
  authMethod: string;
  keyPath?: string;
  group?: string;
  lastConnected?: string;
  /** ProxyJump — missing on old data means disabled. */
  useJump?: boolean;
  jumpHost?: string;
  jumpPort?: number;
  jumpUsername?: string;
  jumpAuthMethod?: JumpAuthMethod;
  jumpKeyPath?: string;
}

// Session types

export interface Session {
  id: string;
  connectionId: string;
  status: SessionStatus;
  createdAt: string;
  errorMessage?: string;
  /** The saved connection config ID (persistent across restarts) */
  configId?: string;
}

export type SessionStatus = 'connecting' | 'connected' | 'disconnected' | 'error';

/**
 * Data carried by an AppError whose `kind === "HostKeyMismatch"` (see error.rs
 * Serialize impl). Frontend branches on this to show the trust-new-key modal
 * instead of a plain error string.
 */
export interface HostKeyMismatchData {
  host: string;
  port: number;
  storedAlgorithm: string;
  storedFingerprint: string;
  presentedAlgorithm: string;
  presentedFingerprint: string;
}

// Quick command types

export type QuickCommandScope = 'global' | 'session';

export interface QuickCommand {
  id: string;
  scope: QuickCommandScope;
  sessionKey?: string | null;
  name: string;
  commands: string[];
  intervalMs: number;
  /** 点击后仅插入内容（最后一行不回车），不自动执行，便于手动改参数 */
  insertOnly: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface QuickCommandInput {
  scope: QuickCommandScope;
  sessionKey?: string | null;
  name: string;
  commands: string[];
  intervalMs: number;
  insertOnly: boolean;
}

export interface QuickCommandPatch {
  scope?: QuickCommandScope;
  sessionKey?: string | null;
  name?: string;
  commands?: string[];
  intervalMs?: number;
  insertOnly?: boolean;
}

// MCP types

export interface McpServer {
  id: string;
  name: string;
  url: string;
  headers: Record<string, string>;
  enabled: boolean;
  trusted: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface McpServerInput {
  name: string;
  url: string;
  headers: Record<string, string>;
  enabled: boolean;
  trusted: boolean;
}

export interface McpTool {
  name: string;
  description: string;
  inputSchema: unknown;
}

export interface McpServerRuntimeStatus {
  serverId: string;
  tools: McpTool[];
  error?: string | null;
  /** True when tools have been probed at least once (cache entry exists). */
  discovered: boolean;
}

export interface McpServerListResponse {
  servers: McpServer[];
  statuses: McpServerRuntimeStatus[];
}

// Agent types

export type AgentMode = 'plan' | 'agent' | 'auto';

export type AgentStatus =
  | 'idle'
  | 'planning'
  | 'executing'
  | 'waiting_approval'
  | 'completed'
  | 'failed'
  | 'cancelled';

export interface AgentTask {
  id: string;
  sessionId: string;
  conversationId: string;
  prompt: string;
  mode: AgentMode;
  status: AgentStatus;
  createdAt: string;
  /** Parent task id — set when this task is a subagent dispatched via the `task` tool. */
  parentTaskId?: string;
}

export interface AgentMessage {
  id: string;
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string;
  timestamp: string;
  toolCall?: ToolCallInfo;
  /** 本轮 assistant 的完整并行 tool_calls（reload / 重建 LLM history 用） */
  toolCalls?: ToolCallInfo[];
  /** Populated for role==='tool' messages created from ToolResultPayload */
  toolResult?: {
    toolName: string;
    summary: string;
    result: string;
    success: boolean;
    blocked: boolean;
    wasTimeout?: boolean;
    wasAborted?: boolean;
    /** Tool call arguments, for display in the tool card */
    arguments?: Record<string, unknown>;
    /** Tool call ID from the LLM, used to reconstruct LLM context history */
    toolCallId?: string;
    /** Backend metadata (e.g. line_position, file_content for edit_file) */
    metadata?: Record<string, unknown>;
  };
  /** True when waiting for LLM response */
  isLoading?: boolean;
  /** True when the LLM is outputting thinking/reasoning content */
  isThinking?: boolean;
  /** Tool call is currently executing, show loading spinner */
  isExecuting?: boolean;
  /** Whether this system message is a retrying indicator (auto-removed on success) */
  isRetrying?: boolean;
  /** Reasoning/thinking content from the model (DeepSeek thinking mode). Passed back to API. */
  reasoningContent?: string;
  /** Relative paths under config images/ for user-attached images */
  imagePaths?: string[];
  /** Current retry attempt number (1-based) for isRetrying messages */
  retryAttempt?: number;
  /** Max retry attempts for isRetrying messages */
  retryMaxAttempts?: number;
  /** Total delay seconds before next retry; UI counts down from timestamp + this */
  retryTotalDelaySecs?: number;
  /** Last error message that triggered the retry */
  retryLastError?: string;
  /** Model approval phase — shown as a distinct progress step on the tool card. */
  modelApproval?: {
    status: 'checking' | 'done';
    decision?: 'approve' | 'route_to_human' | 'block';
    reasons?: string[];
  };
  /** Context compaction indicator — a system message tracking compaction visibility. */
  compaction?: {
    status: 'running' | 'done';
    trigger?: string;
    /** 摘要文本：running 时是实时生成的进度片段，done 时是最终摘要。 */
    summary?: string;
    shadowedMessages?: number;
    shadowedTokens?: number;
    reason?: string;
  };
  /** 持久化消息的 DB row id（`messages.id`，统一 id 域）：load 时填充，
   *  压缩事件据此按 id 定位卡片插入点（取代位置数数与指纹验证）。 */
  dbId?: string;
}

export interface ToolCallInfo {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
  result?: string;
  riskLevel: RiskLevel;
  approved?: boolean;
  /** Reasons from the model approval step, shown when the model routed to human. */
  reasons?: string[];
  /** Preview metadata for approval (e.g. edit_file file_content). */
  metadata?: Record<string, unknown>;
}

export type RiskLevel = 'ReadOnly' | 'LowRisk' | 'Moderate' | 'HighRisk' | 'Destructive';

// Settings

export type CommandListMode = 'allowlist' | 'denylist';

export interface AgentModeSettings {
  listMode: CommandListMode;
  commandList: string[];
  confirmEachCommand: boolean;
  enableModelCommandApproval: boolean;
  /** Custom system prompt for the approval step. Empty = use built-in prompt. */
  modelApprovalPrompt: string;
  systemPrompt: string;
  maxToolRounds: number;
  /** Model context window in tokens. 0 = unset (overflow-triggered compaction only). */
  contextWindow: number;
  confirmEditFile: boolean;
}

export type LlmProviderType = 'openai';

/** 全局共享的网络与重试策略（所有渠道与模型统一生效）。 */
export interface NetPolicy {
  /** 最大自动重试次数，0-10，默认 1。 */
  maxRetries: number;
  /** 重试间隔秒数，1-60，默认 5。 */
  retryDelaySecs: number;
  /** 触发重试的 HTTP 状态码/范围，逗号分隔，如 "408, 429, 500-599"。 */
  retryHttpStatuses: string;
  /** 首字超时秒数，20-250，默认 60。 */
  firstByteTimeoutSecs: number;
  /** 超时后是否自动重试，默认 true。 */
  retryOnTimeout: boolean;
}

/** 一个 OpenAI 兼容的服务接入点（渠道）：OpenRouter / DeepSeek / 硅基流动 / Ollama / OpenAI 官方等。 */
export interface ChannelConfig {
  /** 稳定唯一 ID（uuid）。 */
  id: string;
  /** 展示名称，如「DeepSeek 官方」「硅基流动」。 */
  name: string;
  /** API Base URL，如 `https://api.deepseek.com/v1`。必填（拒绝空值）。 */
  baseUrl: string;
  /** API Key。仅内存持有，不落盘（keychain 按渠道独立存储）。 */
  apiKey?: string;
  /** 是否启用。禁用的渠道不可被解析使用。 */
  enabled: boolean;
}

/** 渠道下的一个具体模型条目。 */
export interface ModelEntry {
  /** 稳定唯一 ID（uuid）。 */
  id: string;
  /** 所属渠道 ID（外键 → ChannelConfig.id）。 */
  channelId: string;
  /** 实际请求 API 时使用的模型名，如 `deepseek-ai/DeepSeek-V3`。 */
  modelName: string;
  /** 展示别名（可选）。空时 UI 用 modelName 展示。 */
  displayName?: string;
  temperature: number;
  /** 是否支持图片输入（多模态）。 */
  vision?: boolean;
  /** 模型上下文窗口（tokens）。0 = 未设置，回落全局 agentModeSettings.contextWindow。 */
  contextWindow?: number;
  /** 该模型特有的请求体参数覆写（如 thinking、top_p）。 */
  extraBody?: Record<string, unknown> | null;
  /**
   * 该模型支持的「思考强度」档位（自填字符串列表，如 `['low','medium','high']`）。
   * 空 = 模型未启用思考强度选择（会话输入条不显示强度选择器，请求体不注入
   * `reasoning_effort`）。值原样透传为请求体顶层 `reasoning_effort`。
   */
  reasoningEfforts?: string[];
}

/** 场景槽位：把「辅助用途」绑定到具体模型。空 = 跟随会话主模型。 */
export interface ModelSlots {
  /** 命令审核模型（enableModelCommandApproval 开启时使用）。空 = 跟随会话模型。 */
  modelApprovalModelId: string;
  /** 上下文压缩摘要模型。空 = 跟随会话模型。 */
  summarizerModelId: string;
}

/** 多渠道多模型注册表（AppSettings 内嵌，随设置持久化）。 */
export interface LlmRegistry {
  channels: ChannelConfig[];
  models: ModelEntry[];
  slots: ModelSlots;
  /** 全局主模型：最近一次在任意会话选择的模型（「最后使用」）。
   *  空/失效 → 解析时回落第一个模型。取代旧版 slots.defaultModelId。 */
  lastUsedModelId?: string;
  /** 全局共享的网络与重试策略（所有渠道/模型统一生效）。 */
  netPolicy: NetPolicy;
}

/** 单个渠道的密钥链状态（仅布尔，后端绝不回传密钥本身）。 */
export interface ChannelKeyStatus {
  channelId: string;
  hasKey: boolean;
}

export interface LlmConfig {
  providerType: LlmProviderType;
  apiKey?: string;  // Optional - loaded from keychain, not persisted to JSON
  model: string;
  baseUrl?: string | null;
  temperature: number;
  maxRetries: number;
  retryDelaySecs: number;
  retryHttpStatuses: string;
  /** 首字超时秒数，20-250，默认 60 */
  firstByteTimeoutSecs: number;
  /** 超时后是否自动重试，默认 true，复用 maxRetries 预算 */
  retryOnTimeout: boolean;
  /** Whether the model accepts image inputs (multimodal / vision). Default false. */
  vision?: boolean;
  /**
   * Free-form JSON object merged into the outgoing chat completion request.
   * Use for provider-specific or otherwise-unexposed parameters
   * (e.g. `thinking`, `top_p`, `max_tokens`, `seed`).
   * Not sent for model-approval calls.
   */
  extraBody?: Record<string, unknown> | null;
}

/** A model entry returned by the provider's /models endpoint. */
export interface ModelInfo {
  id: string;
  ownedBy?: string | null;
  created?: number | null;
}

export interface TerminalColors {
  background: string;
  foreground: string;
  cursor: string;
  cursorAccent: string;
  selectionBackground: string;
  /** Optional; xterm uses this for selected text. Mobile defaults to white for contrast. */
  selectionForeground?: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}

export type WebSearchMode = 'browser' | 'api' | 'html';
export type HttpFetchMode = 'browser' | 'html';
export type WebSearchApiProvider = 'brave' | 'tavily';
/** Bing host used by web_search browser/html modes; default cn */
export type WebSearchEndpoint = 'cn' | 'www';

export interface ExperimentalSettings {
  enableWebSearch: boolean;
  enableHttpFetch: boolean;
  enableCloudPage: boolean;
  /** web_search backend; default browser */
  webSearchMode?: WebSearchMode;
  /** used when webSearchMode === 'api' */
  webSearchApiProvider?: WebSearchApiProvider;
  /** Bing host for browser/html modes; default cn */
  webSearchEndpoint?: WebSearchEndpoint;
  /** http_get backend; independent of webSearchMode; default browser */
  httpFetchMode?: HttpFetchMode;
  /** Allow Agent to render interactive HTML visualizations directly in chat */
  enableHtmlRender?: boolean;
}



export interface NotificationSettings {
  agentApproval: boolean;
  agentQuestion: boolean;
  agentTaskDone: boolean;
  agentTaskFailed: boolean;
  notificationVolume: number;
}

/**
 * 移动端独立通知开关（与桌面端 NotificationSettings 隔离）。
 * 无 notificationVolume：移动端走系统通知通道，不发提示音。
 */
export interface MobileNotificationSettings {
  agentApproval: boolean;
  agentQuestion: boolean;
  agentTaskDone: boolean;
  agentTaskFailed: boolean;
}

/**
 * 移动端后台保活设置（设备本地）。
 * 开启后 App 启动即启动 Android 前台服务，切后台维持 SSH/Agent 运行。
 */
export interface MobileBackgroundSettings {
  keepAliveEnabled: boolean;
}

export interface WorkspaceLayoutSettings {
  sidebarBaseWidth: number;
  agentBaseWidth: number;
  sidebarRatio?: number;
  agentRatio?: number;
  sidebarOpen: boolean;
  agentOpen: boolean;
}

export interface AppSettings {
  terminalColors: TerminalColors;
  fontSize: number;
  fontFamily: string;
  defaultAgentMode: string;
  /** 多渠道多模型注册表（渠道 / 模型 / 场景槽位）。取代旧 llmConfig。 */
  llmRegistry: LlmRegistry;
  agentModeSettings: AgentModeSettings;
  experimentalSettings?: ExperimentalSettings;
  fileManagerPath: string;
  fileManagerPaths: Record<string, string>;
  fileManagerShowHidden: boolean;
  /** Desktop file-manager directory tree width (px). */
  fileManagerTreeWidth: number;
  /** User forced the directory tree closed (still auto-hides when panel is narrow). */
  fileManagerTreeUserHidden: boolean;
  folderUploadCompressionLevel: number;
  panelHeight: number;
  /** Whether to hide thinking/reasoning content in the UI */
  hideThinkingDisplay: boolean;
  /** Privacy mode: mask IP addresses and ports in all UI surfaces (connection
   *  list, quick connect, host-key mismatch modal, chat history, session
   *  descriptions, etc.). The actual SSH connection still uses the real
   *  values — only their on-screen display is masked. */
  privacyMode: boolean;
  notificationSettings: NotificationSettings;
  /** 移动端独立通知开关（设备本地）。桌面端读写无副作用，UI 不暴露。 */
  mobileNotificationSettings: MobileNotificationSettings;
  /** 移动端后台保活设置（设备本地）。 */
  mobileBackgroundSettings: MobileBackgroundSettings;
  workspaceLayout: WorkspaceLayoutSettings;
  /** User-defined protected paths. Writes to anything under these paths
   * require explicit user approval, same as built-in `/etc`, `/boot`, etc. */
  customProtectedPaths: string[];
  /** Command execution timeout in seconds for Agent tools. */
  commandTimeoutSecs: number;
  /** Whether the user has completed the onboarding wizard. */
  hasCompletedOnboarding: boolean;
  /** Disabled plugin IDs. Plugins listed here are scanned but not loaded. */
  disabledPlugins: string[];
  /**
   * Per-plugin authorized capability IDs.
   * If a plugin is not in the map, all declared capabilities are authorized (backward compatible).
   * If a plugin IS in the map, only the listed capabilities are authorized.
   */
  authorizedCapabilities: Record<string, string[]>;
  /** Safe-mode switch: when true, skip all content-script injections on
   *  startup. Used to recover from a plugin whose injected JS hangs the
   *  main window. */
  disableAllInjections: boolean;
}

// LLM token usage — returned by the LLM provider in its API response
export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  reasoningTokens?: number;
  cachedReadTokens?: number;
}

// LLM stream events
export type LlmStreamEvent =
  | { type: 'textDelta'; text: string }
  | { type: 'thinkingDelta'; text: string }
  | { type: 'toolCallStart'; id: string; name: string }
  | { type: 'toolCallDelta'; id: string; argumentsDelta: string }
  | { type: 'usage'; usage: TokenUsage }
  | { type: 'done' }
  | { type: 'error'; message: string }
  | { type: 'retrying'; attempt: number; maxAttempts: number; delaySecs: number; lastError: string }
  // Context compaction visibility — LLM summarization of old history is in
  // progress (can take tens of seconds), completed, or skipped.
  | { type: 'compactionStart'; trigger: string }
  // 压缩进行中的实时进度：summary 文本已生成的累计内容（随流增量推送）。
  | { type: 'compactionProgress'; text: string }
  | { type: 'compactionDone'; summary: string; shadowedMessages: number; shadowedTokens: number; tailDbId: string | null }
  // attempted=false：未开始就跳过（无区间/结构异常），前端不留痕；
  // attempted=true：摘要已跑但失败（截断/未遵循指令/校验不过），前端低调交代。
  | { type: 'compactionSkipped'; reason: string; attempted: boolean }
  // Tool result — emitted as a separate event on the same channel
  | { type: 'toolResult' } & ToolResultPayload
  // Approval request — emitted when user confirmation is needed
  | ApprovalRequestPayload
  // Model approval progress — shows a distinct step on the tool card
  | ModelApprovalStartPayload
  | ModelApprovalDonePayload
  // Question request — agent asks user for input
  | QuestionRequestPayload;

export interface ToolResultPayload {
  type: 'toolResult';
  toolCallId: string;
  toolName: string;
  summary: string;
  result: string;
  success: boolean;
  blocked: boolean;
  wasTimeout?: boolean;
  wasAborted?: boolean;
  arguments: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}

/**
 * Subagent (task tool) launch notification — emitted on the PARENT task's
 * stream channel right after the backend spawned the sub-task. The frontend
 * uses it to register the sub-conversation (hidden from the chat list, live
 * streaming attached) and attach the sub-task's own stream listener.
 */
export interface SubTaskStartPayload {
  type: 'subTaskStart';
  toolCallId: string;
  subTaskId: string;
  subConversationId: string;
  description: string;
  prompt: string;
  /** Parent (main) conversation id — used for hiding, back button, cascade delete. */
  parentConversationId: string;
}

/**
 * Structured sub-task result metadata attached to the parent's toolResult
 * (TaskTool output metadata): { subTaskId, subConversationId, status }.
 */
export interface SubTaskResultMetadata {
  subTaskId: string;
  subConversationId: string;
  status: 'completed' | 'failed' | 'cancelled';
}

export interface ApprovalRequestPayload {
  type: 'approvalRequest';
  toolCallId: string;
  toolName: string;
  arguments: Record<string, unknown>;
  riskLevel: RiskLevel;
  /** Reasons from the model approval step (when it routed to human). */
  reasons?: string[];
  /** Preview metadata (e.g. edit_file file_content / line_position). */
  metadata?: Record<string, unknown>;
  /** Originating task id */
  taskId?: string;
  sessionId?: string;
  conversationId?: string;
  sessionName?: string;
  conversationTitle?: string;
  queueLength?: number;
}

export interface ModelApprovalStartPayload {
  type: 'modelApprovalStart';
  toolCallId: string;
}

export interface ModelApprovalDonePayload {
  type: 'modelApprovalDone';
  toolCallId: string;
  decision: 'approve' | 'route_to_human' | 'block' | 'error';
  reasons: string[];
}

// Question tool types

export interface QuestionOption {
  label: string;
  description: string;
}

export interface QuestionItem {
  question: string;
  header: string;
  options?: QuestionOption[];
  multiple: boolean;
}

export interface QuestionRequestPayload {
  type: 'questionRequest';
  questionId: string;
  questions: QuestionItem[];
  /** Originating task id */
  taskId?: string;
  sessionId?: string;
  conversationId?: string;
  sessionName?: string;
  conversationTitle?: string;
  queueLength?: number;
}

export type InteractionKind = 'approval' | 'question';

export interface ActiveInteractionPayload {
  type: 'interactionActive';
  interactionId: string;
  kind: InteractionKind;
  taskId: string;
  sessionId: string;
  conversationId: string;
  sessionName: string;
  conversationTitle: string;
  queueLength: number;
  approval?: {
    toolCallId: string;
    toolName: string;
    arguments: Record<string, unknown>;
    riskLevel: RiskLevel;
    reasons?: string[];
    metadata?: Record<string, unknown>;
  };
  question?: {
    questionId: string;
    questions: QuestionItem[];
  };
}

export interface QuestionAnswer {
  selected: string[];
  custom: string;
}

// -- stream event --

// Conversation types

export interface AgentConversation {
  id: string;
  connectionId: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  /** 子agent对话（task 工具创建）的父对话 id；主对话无此字段。 */
  parentConversationId?: string;
  /**
   * 会话级模型选择（llmRegistry 模型条目 id）。**仅作旧数据/快照遗留**：
   * 新架构不落盘每会话模型，真正的会话记忆在内存
   * （`sessionModels` store 层 / 后端 `agent_get_session_model`）。
   * 缺省 = 跟随全局最近使用。
   */
  modelId?: string | null;
  /**
   * 会话级思考强度（`reasoning_effort` 档位字符串）：overlay 表达当前
   * 生效模型的档位，后端按「会话 × 模型」双维持久化
   * （`conversations.efforts_json`，重启后记住，启动时装载回内存再 overlay
   * 到这里）：`undefined`/null = 未设置，跟随模型自身默认。
   */
  reasoningEffort?: string | null;
}

export interface StoredMessage {
  id: string;
  conversationId: string;
  role: string;
  content: string;
  timestamp: string;
  createdAt: string;
  toolCallsJson?: string | null;
  reasoningContent?: string | null;
  /** JSON array of relative image paths */
  imagePathsJson?: string | null;
}

/** 活跃消息段加载结果契约 */
export interface ActiveMessagesResult {
  messages: StoredMessage[];
  hasEarlier: boolean;
  checkpointId?: string | null;
}

/** 聊天历史全文搜索的单条会话聚合结果 */
export interface ConversationSearchResult {
  conversationId: string;
  title: string;
  connectionId: string;
  matchedSnippet: string;
  matchCount: number;
  /** 匹配消息 id，按时间升序，最多 200 条 */
  matchedMessageIds: string[];
  updatedAt: string;
}

// Update check types

export interface UpdateCheckResult {
  hasUpdate: boolean;
  latestVersion: string;
  releaseUrl: string;
}

export interface CommandCheckResult {
  allowed: boolean;
  requiresConfirmation: boolean;
  riskLevel: RiskLevel;
  reason: string;
}

// Plan / Todolist types

export type PlanItemStatus = 'pending' | 'in_progress' | 'completed' | 'failed' | 'skipped';

export interface PlanItem {
  id: string;
  title: string;
  status: PlanItemStatus;
  error?: string | null;
}

export interface AgentTaskPlan {
  taskId: string;
  items: PlanItem[];
  currentIndex: number;
  /** 下一个新增 item 的序号（后端持久化字段，前端可选） */
  nextItemSeq?: number;
  /** 反思提醒是否已触发（后端持久化字段，前端可选） */
  reflectionReminded?: boolean;
}

/** 撤回消息后后端返回：消息截断 + 可选 plan 调整 */
export interface TruncateConversationResult {
  deletedMessages: number;
  /** true：已按快照恢复或清空；false：旧数据无快照，plan 未动 */
  planAdjusted: boolean;
  plan: AgentTaskPlan | null;
  planTaskId: string | null;
}

export type PlanStreamEvent =
  | { type: 'plan-created'; items: PlanItem[] }
  | { type: 'plan-item-started'; itemId: string; title: string; index: number; total: number; items: PlanItem[]; currentIndex: number }
  | { type: 'plan-item-completed'; itemId: string; title: string; index: number; total: number; items: PlanItem[]; currentIndex: number }
  | { type: 'plan-item-failed'; itemId: string; title: string; error: string; index: number; total: number; items: PlanItem[]; currentIndex: number }
  | { type: 'plan-item-skipped'; itemId: string; title: string; index: number; total: number; items: PlanItem[]; currentIndex: number }
  | { type: 'plan-completed'; completed: number; total: number; failed: number; items: PlanItem[]; currentIndex: number }
  | { type: 'plan-edited'; ops: unknown[]; items: PlanItem[]; currentIndex: number };

// File manager types

export type FileType = 'file' | 'directory' | 'symlink' | 'pipe' | 'socket' | 'block' | 'character' | 'unknown';

export interface FileEntry {
  name: string;
  path: string;
  type: FileType;
  size: number;
  permissions: string;
  owner: string;
  group: string;
  modifiedAt: string;
  isHidden: boolean;
  linkTarget?: string;
}

export interface SftpFileEntry {
  name: string;
  is_dir: boolean;
  is_file: boolean;
  is_symlink: boolean;
  size: number;
  mode: number;
}

// Skill types

export interface ParsedSkill {
  name: string;
  description: string;
  prompt: string;
}

export interface Skill {
  id: string;
  name: string;
  description: string;
  prompt: string;
  enabled: boolean;
  /** 手动排序位置（仅用户 skill；内置 skill 置顶展示，不参与排序） */
  position: number;
  createdAt: string;
  updatedAt: string;
}

// ──────────── Background Jobs (Job 体系) ────────────
// 后端统一由 command_exec::CommandExecutionManager 管理（submit_background），
// 事件载荷 job://started / job://updated 与 job_list / job_kill 返回 JobInfo。

export type JobStatus = 'running' | 'completed' | 'killed' | 'failed';

export interface JobInfo {
  jobId: string;
  sessionId: string;
  taskId?: string | null;
  description: string;
  command: string;
  status: JobStatus;
  startedAtMillis: number;
  finishedAtMillis?: number | null;
  totalOutputBytes: number;
}

export interface JobOutputResult {
  jobId: string;
  delta: string;
  offset: number;
  status: JobStatus;
  /**
   * 终止来源（仅 killed/断连结算时有值）：user=界面手动终止，
   * agent=Agent job_kill，task=任务停止级联，disconnected=会话断开。
   * 旧数据/未知来源为 null/缺省，展示层保持中性文案。
   */
  cancelReason?: 'user' | 'agent' | 'task' | 'disconnected' | null;
}

/** 启动快照数据包契约（与后端 app_get_bootstrap 对齐） */
export interface AppBootstrapData {
  settings: AppSettings;
  hasApiKey: boolean;
  hasWebSearchApiKey: boolean;
  /** 各渠道密钥是否存在（多渠道模型服务）。 */
  channelKeyStatus?: ChannelKeyStatus[];
  settingsWarning?: string | null;
  connections: SavedConnection[];
  skills: Skill[];
}

