import type { ComponentType, ReactNode } from 'react';

// View Registry types

// 视图挂载点。对外可用的只有 sidebar 和 bottom：
// - sidebar: 左侧面板，由 NavRail 切换
// - bottom: 终端底部 tab，由 BottomTabBar 切换
// center 和 agent 被 builtin 常驻挤占（见 App.tsx 渲染逻辑 + builtinViews.tsx），插件实际无法使用。
export type MountPoint = 'sidebar' | 'center' | 'bottom' | 'agent';
export type NavGroup = 'top' | 'bottom';

export type ViewIcon =
  | { kind: 'react'; node: ReactNode }
  | { kind: 'svg'; path: string }
  | { kind: 'img'; src: string };

export interface ViewProvider {
  id: string;
  pluginId: string;
  mount: MountPoint;
  title: string;
  icon: ViewIcon;
  navGroup?: NavGroup;
  order: number;
  exclusive?: boolean;
  component: () => Promise<{ default: ComponentType }>;
  webviewEntry?: string;
}

// Plugin manifest types

export type IconKind = 'svg' | 'img' | 'emoji';
export type ToolKind = 'ssh' | 'local';
export type RunAt = 'idle' | 'instant';
export type PluginViewMount = 'sidebar' | 'settings';

export interface PluginIconDef {
  kind: IconKind;
  src: string;
}

export interface PluginViewDef {
  id: string;
  mount: PluginViewMount;
  title: string;
  icon?: PluginIconDef;
  navGroup?: NavGroup;
  order: number;
  entry: string;
  exclusive?: boolean;
}

export interface PluginAgentToolDef {
  name: string;
  description: string;
  command: string;
  kind?: ToolKind;
  handler?: string;
  parameters?: unknown;
  riskLevel?: RiskLevel;
}

/**
 * A content-script injection entry. The plugin's JS runs inside the main
 * window and can manipulate the DOM freely (IPC calls still go through the
 * capability-checked proxy). CSS is injected as a global `<style>` tag.
 */
export interface PluginInjectionDef {
  /** Unique id within the plugin (e.g. "main-ui"). */
  id: string;
  /**
   * Which main-UI regions this injection targets. Values match `data-region`
   * attributes: "sidebar" / "center" / "agent" / "terminal" / "settings" /
   * "sessions" / "skills" / "mcp" / "agent-panel". "*" means always inject.
   */
  matches: string[];
  /** CSS file paths relative to the plugin root, injected as `<style>` tags. */
  styles: string[];
  /** JS file paths relative to the plugin root, executed with the `marcel`
   *  runtime API as the argument. */
  scripts: string[];
  /** When to inject: "idle" (default) or "instant". */
  runAt: RunAt;
  /** Sort weight for multi-plugin ordering (lower = earlier). */
  order: number;
}

export interface PluginManifest {
  id: string;
  version: string;
  name: string;
  publisher?: string;
  description?: string;
  capabilities: string[];
  views: PluginViewDef[];
  agentTools: PluginAgentToolDef[];
  configView?: string;
  /** Content-script injections. Requires the `ui.inject` capability. */
  injections: PluginInjectionDef[];
  /**
   * Minimum app version this plugin is compatible with (optional). When the
   * running app version is lower, the plugin is auto-disabled: the backend
   * refuses to load it and the settings UI shows the required version.
   */
  minAppVersion?: string;
}

export interface PluginHttpRequest {
  url: string;
  method?: string;
  headers?: Record<string, string>;
  body?: string;
}

export interface PluginHttpResponse {
  status: number;
  headers: Record<string, string>;
  body: string;
  url: string;
}

/** Market icon: emoji glyph or https image URL. */
export interface MarketIcon {
  kind: 'emoji' | 'img';
  value: string;
}

/** One plugin entry in the market index (generated by the market repo bot). */
export interface MarketPlugin {
  id: string;
  name: string;
  version: string;
  publisher: string;
  minAppVersion?: string | null;
  description: string;
  capabilities: string[];
  category: string;
  icon?: MarketIcon | null;
  repoUrl: string;
  updatedAt: string;
}

/** Market index document served by the market repository. */
export interface MarketIndex {
  generatedAt: string;
  plugins: MarketPlugin[];
}

/** Detail payload: plugin.json + README.md from the plugin's GitHub repo. */
export interface MarketDetail {
  manifest: PluginManifest | null;
  readme: string | null;
}

/** Result of `plugin_install`. The plugin takes effect after a restart. */
export interface PluginInstallResult {
  id: string;
  name: string;
  version: string;
  restartRequired: boolean;
}

/** Progress pushed by `plugin_install` via `plugin-install-progress` events.
 *  `phase: "downloading"` uses byte counts; `phase: "extracting"` uses zip
 *  entry counts. `total === 0` means unknown (indeterminate progress bar). */
export interface PluginInstallProgress {
  installId: string;
  phase: 'downloading' | 'extracting';
  received: number;
  total: number;
}

/**
 * Diff returned by `plugin_reload` / emitted via `plugin-registry-changed`.
 * `changed` lists plugin ids whose manifest or enabled-state changed since the
 * previous reload; `removed` lists ids no longer on disk. Callers should
 * destroy/recreate webviews + injections for these plugins only (incremental
 * refresh instead of nuke-and-rebuild).
 */
export interface ReloadDiff {
  allIds: string[];
  changed: string[];
  removed: string[];
}

// Connection types

export interface JumpConfig {
  host: string;
  port: number;
  username: string;
  authMethod: AuthMethod;
}

export interface ConnectionConfig {
  host: string;
  port: number;
  username: string;
  authMethod: AuthMethod;
  /** Saved connection ID, used by Agent tools for password lookup (sudo auto-fill). */
  connectionId?: string;
  /**
   * User has explicitly opted to trust a new (mismatching) host key. Only set
   * after the user confirms the HostKeyMismatch modal. Drives the backend to
   * `KnownHostsStore::replace` instead of rejecting the handshake.
   */
  trustNewHostKey?: boolean;
  /** Optional ProxyJump hop. */
  jump?: JumpConfig;
}

export type AuthMethod =
  | { type: 'Password'; password: string }
  | { type: 'PrivateKey'; keyPath: string; passphrase?: string }
  | { type: 'Agent' };

/** Jump auth mode stored on SavedConnection (not runtime credentials). */
export type JumpAuthMethod = 'withTarget' | 'Password' | 'PrivateKey';

export interface SavedConnection {
  id: string;
  name: string;
  host: string;
  port: number;
  username: string;
  authMethod: string;
  keyPath?: string;
  group?: string;
  lastConnected?: string;
  /** ProxyJump — missing on old data means disabled. */
  useJump?: boolean;
  jumpHost?: string;
  jumpPort?: number;
  jumpUsername?: string;
  jumpAuthMethod?: JumpAuthMethod;
  jumpKeyPath?: string;
}

// Session types

export interface Session {
  id: string;
  connectionId: string;
  status: SessionStatus;
  createdAt: string;
  errorMessage?: string;
  /** The saved connection config ID (persistent across restarts) */
  configId?: string;
}

export type SessionStatus = 'connecting' | 'connected' | 'disconnected' | 'error';

/**
 * Data carried by an AppError whose `kind === "HostKeyMismatch"` (see error.rs
 * Serialize impl). Frontend branches on this to show the trust-new-key modal
 * instead of a plain error string.
 */
export interface HostKeyMismatchData {
  host: string;
  port: number;
  storedAlgorithm: string;
  storedFingerprint: string;
  presentedAlgorithm: string;
  presentedFingerprint: string;
}

// Quick command types

export type QuickCommandScope = 'global' | 'session';

export interface QuickCommand {
  id: string;
  scope: QuickCommandScope;
  sessionKey?: string | null;
  name: string;
  commands: string[];
  intervalMs: number;
  createdAt: string;
  updatedAt: string;
}

export interface QuickCommandInput {
  scope: QuickCommandScope;
  sessionKey?: string | null;
  name: string;
  commands: string[];
  intervalMs: number;
}

export interface QuickCommandPatch {
  scope?: QuickCommandScope;
  sessionKey?: string | null;
  name?: string;
  commands?: string[];
  intervalMs?: number;
}

// MCP types

export interface McpServer {
  id: string;
  name: string;
  url: string;
  headers: Record<string, string>;
  enabled: boolean;
  trusted: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface McpServerInput {
  name: string;
  url: string;
  headers: Record<string, string>;
  enabled: boolean;
  trusted: boolean;
}

export interface McpTool {
  name: string;
  description: string;
  inputSchema: unknown;
}

export interface McpServerRuntimeStatus {
  serverId: string;
  tools: McpTool[];
  error?: string | null;
  /** True when tools have been probed at least once (cache entry exists). */
  discovered: boolean;
}

export interface McpServerListResponse {
  servers: McpServer[];
  statuses: McpServerRuntimeStatus[];
}

// Agent types

export type AgentMode = 'plan' | 'agent' | 'auto';

export type AgentStatus =
  | 'idle'
  | 'planning'
  | 'executing'
  | 'waiting_approval'
  | 'completed'
  | 'failed'
  | 'cancelled';

export interface AgentTask {
  id: string;
  sessionId: string;
  conversationId: string;
  prompt: string;
  mode: AgentMode;
  status: AgentStatus;
  createdAt: string;
  /** Parent task id — set when this task is a subagent dispatched via the `task` tool. */
  parentTaskId?: string;
}

export interface AgentMessage {
  id: string;
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string;
  timestamp: string;
  toolCall?: ToolCallInfo;
  /** 本轮 assistant 的完整并行 tool_calls（reload / 重建 LLM history 用） */
  toolCalls?: ToolCallInfo[];
  /** Populated for role==='tool' messages created from ToolResultPayload */
  toolResult?: {
    toolName: string;
    summary: string;
    result: string;
    success: boolean;
    blocked: boolean;
    wasTimeout?: boolean;
    wasAborted?: boolean;
    /** Tool call arguments, for display in the tool card */
    arguments?: Record<string, unknown>;
    /** Tool call ID from the LLM, used to reconstruct LLM context history */
    toolCallId?: string;
    /** Backend metadata (e.g. line_position, file_content for edit_file) */
    metadata?: Record<string, unknown>;
  };
  /** True when waiting for LLM response */
  isLoading?: boolean;
  /** True when the LLM is outputting thinking/reasoning content */
  isThinking?: boolean;
  /** Tool call is currently executing, show loading spinner */
  isExecuting?: boolean;
  /** Whether this system message is a retrying indicator (auto-removed on success) */
  isRetrying?: boolean;
  /** Reasoning/thinking content from the model (DeepSeek thinking mode). Passed back to API. */
  reasoningContent?: string;
  /** Relative paths under config images/ for user-attached images */
  imagePaths?: string[];
  /** Current retry attempt number (1-based) for isRetrying messages */
  retryAttempt?: number;
  /** Max retry attempts for isRetrying messages */
  retryMaxAttempts?: number;
  /** Total delay seconds before next retry; UI counts down from timestamp + this */
  retryTotalDelaySecs?: number;
  /** Last error message that triggered the retry */
  retryLastError?: string;
  /** Model approval phase — shown as a distinct progress step on the tool card. */
  modelApproval?: {
    status: 'checking' | 'done';
    decision?: 'approve' | 'route_to_human' | 'block';
    reasons?: string[];
  };
}

export interface ToolCallInfo {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
  result?: string;
  riskLevel: RiskLevel;
  approved?: boolean;
  /** Reasons from the model approval step, shown when the model routed to human. */
  reasons?: string[];
  /** Preview metadata for approval (e.g. edit_file file_content). */
  metadata?: Record<string, unknown>;
}

export type RiskLevel = 'ReadOnly' | 'LowRisk' | 'Moderate' | 'HighRisk' | 'Destructive';

// Settings

export type CommandListMode = 'allowlist' | 'denylist';

export interface AgentModeSettings {
  listMode: CommandListMode;
  commandList: string[];
  confirmEachCommand: boolean;
  enableModelCommandApproval: boolean;
  /** Model name override for the approval step. Empty = use main model. */
  modelApprovalModel: string;
  /** Custom system prompt for the approval step. Empty = use built-in prompt. */
  modelApprovalPrompt: string;
  systemPrompt: string;
  maxToolRounds: number;
  /** Enable LLM context compression to stay within model window limits */
  compactContext: boolean;
  confirmEditFile: boolean;
}

export type LlmProviderType = 'openai';

export interface LlmConfig {
  providerType: LlmProviderType;
  apiKey?: string;  // Optional - loaded from keychain, not persisted to JSON
  model: string;
  baseUrl?: string | null;
  temperature: number;
  maxRetries: number;
  retryDelaySecs: number;
  retryHttpStatuses: string;
  /** Whether the model accepts image inputs (multimodal / vision). Default false. */
  vision?: boolean;
  /**
   * Free-form JSON object merged into the outgoing chat completion request.
   * Use for provider-specific or otherwise-unexposed parameters
   * (e.g. `thinking`, `top_p`, `max_tokens`, `seed`).
   * Not sent for model-approval calls.
   */
  extraBody?: Record<string, unknown> | null;
}

/** A model entry returned by the provider's /models endpoint. */
export interface ModelInfo {
  id: string;
  ownedBy?: string | null;
  created?: number | null;
}

export interface TerminalColors {
  background: string;
  foreground: string;
  cursor: string;
  cursorAccent: string;
  selectionBackground: string;
  /** Optional; xterm uses this for selected text. Mobile defaults to white for contrast. */
  selectionForeground?: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}

export type WebSearchMode = 'browser' | 'api' | 'html';
export type HttpFetchMode = 'browser' | 'html';
export type WebSearchApiProvider = 'brave' | 'tavily';
/** Bing host used by web_search browser/html modes; default cn */
export type WebSearchEndpoint = 'cn' | 'www';

export interface ExperimentalSettings {
  enableWebSearch: boolean;
  enableHttpFetch: boolean;
  enableCloudPage: boolean;
  /** web_search backend; default browser */
  webSearchMode?: WebSearchMode;
  /** used when webSearchMode === 'api' */
  webSearchApiProvider?: WebSearchApiProvider;
  /** Bing host for browser/html modes; default cn */
  webSearchEndpoint?: WebSearchEndpoint;
  /** http_get backend; independent of webSearchMode; default browser */
  httpFetchMode?: HttpFetchMode;
}



export interface NotificationSettings {
  agentApproval: boolean;
  agentQuestion: boolean;
  agentTaskDone: boolean;
  agentTaskFailed: boolean;
  notificationVolume: number;
}

/**
 * 移动端独立通知开关（不参与云端同步，与桌面端 NotificationSettings 隔离）。
 * 无 notificationVolume：移动端走系统通知通道，不发提示音。
 */
export interface MobileNotificationSettings {
  agentApproval: boolean;
  agentQuestion: boolean;
  agentTaskDone: boolean;
  agentTaskFailed: boolean;
}

/**
 * 移动端后台保活设置（不参与云端同步）。
 * 开启后 App 启动即启动 Android 前台服务，切后台维持 SSH/Agent 运行。
 */
export interface MobileBackgroundSettings {
  keepAliveEnabled: boolean;
}

export interface WorkspaceLayoutSettings {
  sidebarBaseWidth: number;
  agentBaseWidth: number;
  sidebarRatio?: number;
  agentRatio?: number;
  sidebarOpen: boolean;
  agentOpen: boolean;
}

export interface AppSettings {
  terminalColors: TerminalColors;
  fontSize: number;
  fontFamily: string;
  defaultAgentMode: string;
  llmConfig?: LlmConfig | null;
  agentModeSettings: AgentModeSettings;
  experimentalSettings?: ExperimentalSettings;
  fileManagerPath: string;
  fileManagerPaths: Record<string, string>;
  fileManagerShowHidden: boolean;
  /** Desktop file-manager directory tree width (px). */
  fileManagerTreeWidth: number;
  /** User forced the directory tree closed (still auto-hides when panel is narrow). */
  fileManagerTreeUserHidden: boolean;
  folderUploadCompressionLevel: number;
  panelHeight: number;
  /** Whether to hide thinking/reasoning content in the UI */
  hideThinkingDisplay: boolean;
  /** Privacy mode: mask IP addresses and ports in all UI surfaces (connection
   *  list, quick connect, host-key mismatch modal, chat history, session
   *  descriptions, etc.). The actual SSH connection still uses the real
   *  values — only their on-screen display is masked. */
  privacyMode: boolean;
  notificationSettings: NotificationSettings;
  /** 移动端独立通知开关（不参与云端同步）。桌面端读写无副作用，UI 不暴露。 */
  mobileNotificationSettings: MobileNotificationSettings;
  /** 移动端后台保活设置（不参与云端同步）。 */
  mobileBackgroundSettings: MobileBackgroundSettings;
  workspaceLayout: WorkspaceLayoutSettings;
  /** User-defined protected paths. Writes to anything under these paths
   * require explicit user approval, same as built-in `/etc`, `/boot`, etc. */
  customProtectedPaths: string[];
  /** Command execution timeout in seconds for Agent tools. */
  commandTimeoutSecs: number;
  /** Whether the user has completed the onboarding wizard. */
  hasCompletedOnboarding: boolean;
  /** Whether the user has accepted the cross-device sync disclaimer (first visit only). */
  hasAcceptedSyncDisclaimer: boolean;
  /** Disabled plugin IDs. Plugins listed here are scanned but not loaded. */
  disabledPlugins: string[];
  /**
   * Per-plugin authorized capability IDs.
   * If a plugin is not in the map, all declared capabilities are authorized (backward compatible).
   * If a plugin IS in the map, only the listed capabilities are authorized.
   */
  authorizedCapabilities: Record<string, string[]>;
  /** Safe-mode switch: when true, skip all content-script injections on
   *  startup. Used to recover from a plugin whose injected JS hangs the
   *  main window. */
  disableAllInjections: boolean;
}

// LLM token usage — returned by the LLM provider in its API response
export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  reasoningTokens?: number;
  cachedReadTokens?: number;
}

// LLM stream events
export type LlmStreamEvent =
  | { type: 'textDelta'; text: string }
  | { type: 'thinkingDelta'; text: string }
  | { type: 'toolCallStart'; id: string; name: string }
  | { type: 'toolCallDelta'; id: string; argumentsDelta: string }
  | { type: 'usage'; usage: TokenUsage }
  | { type: 'done' }
  | { type: 'error'; message: string }
  | { type: 'retrying'; attempt: number; maxAttempts: number; delaySecs: number; lastError: string }
  // Tool result — emitted as a separate event on the same channel
  | { type: 'toolResult' } & ToolResultPayload
  // Approval request — emitted when user confirmation is needed
  | ApprovalRequestPayload
  // Model approval progress — shows a distinct step on the tool card
  | ModelApprovalStartPayload
  | ModelApprovalDonePayload
  // Question request — agent asks user for input
  | QuestionRequestPayload;

export interface ToolResultPayload {
  type: 'toolResult';
  toolCallId: string;
  toolName: string;
  summary: string;
  result: string;
  success: boolean;
  blocked: boolean;
  wasTimeout?: boolean;
  wasAborted?: boolean;
  arguments: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}

/**
 * Subagent (task tool) launch notification — emitted on the PARENT task's
 * stream channel right after the backend spawned the sub-task. The frontend
 * uses it to register the sub-conversation (hidden from the chat list, live
 * streaming attached) and attach the sub-task's own stream listener.
 */
export interface SubTaskStartPayload {
  type: 'subTaskStart';
  toolCallId: string;
  subTaskId: string;
  subConversationId: string;
  description: string;
  prompt: string;
  /** Parent (main) conversation id — used for hiding, back button, cascade delete. */
  parentConversationId: string;
}

/**
 * Structured sub-task result metadata attached to the parent's toolResult
 * (TaskTool output metadata): { subTaskId, subConversationId, status }.
 */
export interface SubTaskResultMetadata {
  subTaskId: string;
  subConversationId: string;
  status: 'completed' | 'failed' | 'cancelled';
}

export interface ApprovalRequestPayload {
  type: 'approvalRequest';
  toolCallId: string;
  toolName: string;
  arguments: Record<string, unknown>;
  riskLevel: RiskLevel;
  /** Reasons from the model approval step (when it routed to human). */
  reasons?: string[];
  /** Preview metadata (e.g. edit_file file_content / line_position). */
  metadata?: Record<string, unknown>;
  /**
   * Originating task id — injected by the frontend listener (the backend event
   * carries no task id; the listener knows it from the channel it subscribed
   * to). Used to route approve/reject back to the correct task (subagents
   * run on their own channel while the active task may still be the parent).
   */
  taskId?: string;
}

export interface ModelApprovalStartPayload {
  type: 'modelApprovalStart';
  toolCallId: string;
}

export interface ModelApprovalDonePayload {
  type: 'modelApprovalDone';
  toolCallId: string;
  decision: 'approve' | 'route_to_human' | 'block' | 'error';
  reasons: string[];
}

// Question tool types

export interface QuestionOption {
  label: string;
  description: string;
}

export interface QuestionItem {
  question: string;
  header: string;
  options?: QuestionOption[];
  multiple: boolean;
}

export interface QuestionRequestPayload {
  type: 'questionRequest';
  questionId: string;
  questions: QuestionItem[];
  /**
   * Originating task id — injected by the frontend listener (see
   * ApprovalRequestPayload.taskId). Used to route answers back to the
   * correct task.
   */
  taskId?: string;
}

export interface QuestionAnswer {
  selected: string[];
  custom: string;
}

// -- stream event --

// Conversation types

export interface AgentConversation {
  id: string;
  connectionId: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  /** 子agent对话（task 工具创建）的父对话 id；主对话无此字段。 */
  parentConversationId?: string;
}

export interface StoredMessage {
  id: string;
  conversationId: string;
  role: string;
  content: string;
  timestamp: string;
  createdAt: string;
  toolCallsJson?: string | null;
  reasoningContent?: string | null;
  /** JSON array of relative image paths */
  imagePathsJson?: string | null;
}

/** 聊天历史全文搜索的单条会话聚合结果 */
export interface ConversationSearchResult {
  conversationId: string;
  title: string;
  connectionId: string;
  matchedSnippet: string;
  matchCount: number;
  /** 匹配消息 id，按时间升序，最多 200 条 */
  matchedMessageIds: string[];
  updatedAt: string;
}

// Update check types

export interface UpdateCheckResult {
  hasUpdate: boolean;
  latestVersion: string;
  releaseUrl: string;
}

export interface CommandCheckResult {
  allowed: boolean;
  requiresConfirmation: boolean;
  riskLevel: RiskLevel;
  reason: string;
}

// Plan / Todolist types

export type PlanItemStatus = 'pending' | 'in_progress' | 'completed' | 'failed' | 'skipped';

export interface PlanItem {
  id: string;
  title: string;
  status: PlanItemStatus;
  error?: string | null;
}

export interface AgentTaskPlan {
  taskId: string;
  items: PlanItem[];
  currentIndex: number;
  /** 下一个新增 item 的序号（后端持久化字段，前端可选） */
  nextItemSeq?: number;
  /** 反思提醒是否已触发（后端持久化字段，前端可选） */
  reflectionReminded?: boolean;
}

/** 撤回消息后后端返回：消息截断 + 可选 plan 调整 */
export interface TruncateConversationResult {
  deletedMessages: number;
  /** true：已按快照恢复或清空；false：旧数据无快照，plan 未动 */
  planAdjusted: boolean;
  plan: AgentTaskPlan | null;
  planTaskId: string | null;
}

export type PlanStreamEvent =
  | { type: 'plan-created'; items: PlanItem[] }
  | { type: 'plan-item-started'; itemId: string; title: string; index: number; total: number; items: PlanItem[]; currentIndex: number }
  | { type: 'plan-item-completed'; itemId: string; title: string; index: number; total: number; items: PlanItem[]; currentIndex: number }
  | { type: 'plan-item-failed'; itemId: string; title: string; error: string; index: number; total: number; items: PlanItem[]; currentIndex: number }
  | { type: 'plan-item-skipped'; itemId: string; title: string; index: number; total: number; items: PlanItem[]; currentIndex: number }
  | { type: 'plan-completed'; completed: number; total: number; failed: number; items: PlanItem[]; currentIndex: number }
  | { type: 'plan-edited'; ops: unknown[]; items: PlanItem[]; currentIndex: number };

// File manager types

export type FileType = 'file' | 'directory' | 'symlink' | 'pipe' | 'socket' | 'block' | 'character' | 'unknown';

export interface FileEntry {
  name: string;
  path: string;
  type: FileType;
  size: number;
  permissions: string;
  owner: string;
  group: string;
  modifiedAt: string;
  isHidden: boolean;
  linkTarget?: string;
}

export interface SftpFileEntry {
  name: string;
  is_dir: boolean;
  is_file: boolean;
  is_symlink: boolean;
  size: number;
  mode: number;
}

// Skill types

export interface ParsedSkill {
  name: string;
  description: string;
  prompt: string;
}

export interface Skill {
  id: string;
  name: string;
  description: string;
  prompt: string;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}

// ──────────── 跨设备同步（与 Rust sync 模块对齐，camelCase） ────────────

/** 一级同步分类（与 src-tauri/src/sync/profile.rs SyncCategory 对齐） */
export type SyncCategory =
  | 'connections'
  | 'quickCommands'
  | 'skills'
  | 'mcpServers'
  | 'conversations'
  | 'terminalSettings'
  | 'modelService'
  | 'agentPolicy'
  | 'displaySettings'
  | 'agentTools'
  | 'secrets';

/** 平台标识（与 sync/profile.rs Platform 对齐，lowercase 序列化） */
export type SyncPlatform = 'desktop' | 'mobile';

/** 同步状态机（与 sync/scheduler.rs SyncState 对齐，camelCase 序列化） */
export type SyncState = 'idle' | 'pushing' | 'pulling' | 'error' | 'notConfigured';

/** pull 进度（与 sync/scheduler.rs SyncProgress 对齐） */
export interface SyncProgress {
  /** 本次 pull 待处理的 item 总数（profile 过滤后） */
  total: number;
  /** 已处理 item 数 */
  done: number;
}

/**
 * sync_profile：用户选择的同步项集合。
 * Rust 端用 HashSet<SyncCategory>，序列化后是数组；前端用数组以保持顺序与可遍历。
 */
export interface SyncProfile {
  /** 开启的一级分类列表 */
  enabledCategories: SyncCategory[];
  /** 字段级排除清单（用户在冲突 UI 选"永久跳过"时加入）
   *  存储完整 key 字符串（如 "settings.fontSize"）
   *  与 Rust 端 HashSet<String> 对齐，序列化为数组 */
  excludedKeys: string[];
  /** 结构版本（与后端 SYNC_PROFILE_SCHEMA_VERSION 对齐）。
   *  老版本缺省 = v1，后端加载时会自动迁移补上新增分类默认开启项 */
  schemaVersion?: number;
}

/** 同步摘要（GET sync_get_summary 返回） */
export interface SyncSummary {
  /** 是否已完成配对（sync_key + device_id + api_key 全部就绪） */
  configured: boolean;
  /** 服务器 URL（未配置时为 null） */
  serverUrl: string | null;
  /** 本设备 ID（未配置时为 null） */
  deviceId: string | null;
  /** 平台标识：'desktop' | 'mobile' */
  platform: string;
  /** 当前 sync_profile */
  profile: SyncProfile;
  /** 当前同步状态机值 */
  state: SyncState;
  /** 待 push 的本地变更数 */
  pendingCount: number;
  /** 最近错误信息（无错为 null） */
  error: string | null;
  /** pull 进度（pulling 时非 null） */
  progress: SyncProgress | null;
}

/** sync-state-changed 事件 payload */
export interface SyncStateEvent {
  state: SyncState;
  pendingCount: number;
  error: string | null;
  progress: SyncProgress | null;
}

/** 已配对设备信息 */
export interface SyncDeviceInfo {
  /** 设备 ID（UUID） */
  deviceId: string;
  /** 平台：'desktop' | 'mobile' */
  platform: SyncPlatform;
  /** 最后活跃时间（ISO 8601 字符串） */
  lastSeenAt: string;
}

/** 账户配额使用情况（GET sync_get_quota 返回；旧服务端无此端点时前端静默隐藏配额行） */
export interface SyncQuota {
  /** 已用字节数（snapshots + sync_profiles） */
  quotaUsedBytes: number;
  /** 配额上限字节数；0 = 无限制 */
  quotaLimitBytes: number;
  /** 'hosted' | 'self-hosted' */
  mode: string;
}

/** sync_pair_first / sync_pair_join 返回值 */
export interface SyncPairResult {
  /** 第一台设备返回新生成的配置码（仅此一次，用户必须手抄保存）；其他设备返回 null */
  configCode: string | null;
  /** 是否是第一台设备（true = 新账户，false = 加入已有账户） */
  isFirstDevice: boolean;
}

/** sync_reset_account 返回值 */
export interface SyncResetResult {
  success: boolean;
  error: string | null;
}

// ──────────── 冲突解决（与 Rust sync::engine 对齐） ────────────

/**
 * 待解决的同步冲突项。
 * pull 时检测到本地和远程都改了同一 key 且值不同，缓存到内存等用户决策。
 */
export interface SyncPendingConflict {
  /** 冲突的 key（如 `settings.fontSize`、`connections.abc`） */
  key: string;
  /** 远程版本号 */
  remoteVersion: number;
  /** base：上次同步的值（明文 JSON 字符串），首次同步时为 null */
  base: string | null;
  /** ours：当前本地值（明文 JSON 字符串），删除时为 null */
  ours: string | null;
  /** theirs：远程值（明文 JSON 字符串），远程删除时为 null */
  theirs: string | null;
}

/**
 * 用户在 UI 选择的冲突解决动作（与 Rust ConflictActionDto 对齐）。
 * 使用 serde tag = "type" 序列化。
 */
export type SyncConflictAction =
  | { type: 'ours' }
  | { type: 'theirs' }
  | { type: 'skipOnce' }
  | { type: 'skipForever' }
  | { type: 'custom'; value: string }
  | { type: 'fork' };

/** sync_resolve_conflict / sync_resolve_all_conflicts 返回值 */
export interface SyncResolveResult {
  /** "pushNeeded" | "appliedTheirs" | "skipped" | "excluded" */
  outcome: string;
  /** 是否已自动调度 push */
  pushTriggered: boolean;
}

/** sync-conflicts-detected 事件 payload */
export interface SyncConflictsEvent {
  /** 所有待解决的冲突（含 base/ours/theirs 明文 JSON） */
  conflicts: SyncPendingConflict[];
  /** 冲突数量 */
  count: number;
}
